### ISSUE TITLE
Fix tracetest.span.duration precision so direct timing comparisons do not fail

### ISSUE THREAD

**Issue by cescoferraro** [kubeshop/tracetest#1203]
When a user selects the `tracetest.span.duration` attribute when creating an assertion, the frontend fills out the expected value with the value we receive from the backend.

![Image](https://user-images.githubusercontent.com/6259987/190013717-816d9dbc-2699-4544-8294-4740d87fe7d2.png)

But this asssertions always fail. It seems that there is a precision issue when comparing the values.

![Image](https://user-images.githubusercontent.com/6259987/190013718-66ac5880-133e-4f80-b763-620c1e70ba94.png)

`AC1:`
User should be able to write te following successful assertion `tracetest.span.duration = {{x}}ms` and x would be de tracetest.span.duration the backend is returning to the frontend.

**Comment by mathnogueira** [comment]
Some explanation of why this comparison fails so we can discuss a better way of handling this.

All duration attributes are stored as numbers so we don't lose precision when comparing them. So you might be `42ms` but in reality, the duration can be any number between [`42000000`, `42999999`].

Now, when a user creates an assertion and set a duration to be compared with a span attribute, we have to convert back from the formatted value to the real number. As `42ms` doesn't have much precision, it is converted to `42000000`. Thus, when you compare the span attribute value with the assertion expected value, we have this weird (but understandable) outcome. Because `42687451 != 42000000`.

I think that the easiest way of comparing those values in a deterministic way would be by removing the precision from the span attribute at the moment of comparison. We could easily do that by executing:

```go
// value = 42687451
valueInTimeUnit := traces.ConvertNanoSecondsIntoProperTimeUnit(value)
// valueInTimeUnit = 42ms
value = traces.ConvertTimeFieldIntoNanoSeconds(valueInTimeUnit)
// value = 42000000
```
