### ISSUE TITLE
[Transactions] When does a transaction fail?

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1504]
While working on transactions there were a couple of questions that came to mind.

1. When should we consider a transaction as failed?
2. Should the transaction be stopped as soon as one of its tests fails (assertions, trigger)?
3. Should the result of a transaction be the summary of passed/failed specs from its tests?

**Comment by mathnogueira** [comment]
I expect transactions to be set as failed as soon as any step fails. And if one fails, the next steps shouldn't be executed.

I would set the summary for a transaction as the number of steps that passed and the amount that failed (this should be either 0 or 1 based on the rules I talked about above)

**Comment by schoren** [comment]
My thoughs: 

1. A transaction should be considered failed when a test fails. That means, there was an error in either the trigger or in fetching the traces. Not passing tests are not considered failures in this case.

2. Since a transaction is an ordered list of steps that are most likely correlated, as soon as a  step fails it needs to stop, because other steps might depend on it

3. If a transaction is completed without error, the summary should be the sum of fail/pass. If it has an error, it shuold be treated as when a test has an error

**Comment by jorgeepc** [comment]
1. Should fail when there is an error in one of the steps. Agree with Sebastian about not considering Test Specs here.
2. Yes, we should stop execution. Considering the same logic for failure (not test specs).
3. The summary should be the number of passed steps + failed step if it exists + not executed steps.

**Comment by cescoferraro** [comment]
When should we consider a transaction as failed?
As soon as on test fails. But we could have a retry config similar to Cypress. So it tries again x number of times.
The default should be zero IMO.

Should the transaction be stopped as soon as one of its tests fails (assertions, trigger)?
I think it should stop, but this can be something we can leverage for monetization in the feature. Again, the same way Cypress does. You need to pay for it to stop when a test fails.

Should the result of a transaction be the summary of passed/failed specs from its tests?
Yes

**Comment by kdhamric** [comment]
Agree with everything above. My guess is we may / will be driven to add options at the step/ test level, such as X retries or 'stop on any test spec failures', but let's start simple and have users drive us to increase complexity.

**Comment by xoscar** [comment]
Let's discuss this tomorrow during planning, thanks for the feedback team! <3
