### ISSUE TITLE
Once I have seen the onboarding I cannot see it again

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1733]
Launched the latest version and was viewing the onboarding. Went back to view it again, trying to launch it from the ? icon at the top right. Onboarding would not launch for me. Tried to refresh with same results.

As a user,
I should be able to view the onboarding and exit
If I come back and want to see it again, 
I should be able to launch it from the ?, Show Onboarding link

**Comment by olha23** [comment]
Additional comment
On the last onboarding card (when we show step 5 of 5) we don’t need to show buttons- skip, back and next. Instead of them just show one button - Done
<img width="402" alt="Screenshot 2022-12-22 at 3 17 33 PM" src="https://user-images.githubusercontent.com/5725840/209210415-8ae69f02-d951-4226-aba8-b31a43f1e71c.png">

**Comment by olha23** [comment]
one more https://www.loom.com/share/a376287f236c47be8ebec1fa574891e8

**Comment by olha23** [comment]
also will be great if we make the footer part in that tooltips more alegant, now its bigger that header. And make Next text button primary. Check the mockups here https://www.figma.com/file/TMShLwGmcTwX7uRodvyRoE/Tracetest?node-id=257%3A7844&t=hb14MA8dG54jfCZv-1

**Comment by olha23** [comment]
one more strange behaviour:
we show Take a quick tour proposition on the main screen but don’t have tour for this page, when you click Show me around - nothing happens 
<img width="1434" alt="Screenshot 2022-12-23 at 4 07 17 PM" src="https://user-images.githubusercontent.com/5725840/209401721-c6574fd1-16ab-43a6-ad95-c94f36ad541b.png">
