### ISSUE TITLE
Still collecting and showing trace info when in no trace mode 

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1739]
When setup to use the OpenTelemetry Collector, if you delete the configuration and enter the no trace mode, you sometimes get a trace or pieces of spans from the trace. Expected behavior would be that you would only receive the top 'response' span.

Showing getting a full trace while in no trace mode:
https://www.loom.com/share/a11e1a97743c4496acd513b3bf6893b7

Showing getting a messaging span while in no trace mode:
![image](https://user-images.githubusercontent.com/1385894/209348633-421cefbb-8c91-425b-8969-57a495d3abb0.png)

**Comment by mathnogueira** [comment]
I finally understood why that's happening. Because even though the data store is not configured, tracetest is still running the OTLP server (which is always on) and your otel collector is stlll sending the trace to it.

So the poller is working fine. The problem is that the trace is being updated in the background when the collector sends the trace.

We would probably need a way of disabling that server to prevent it from updating the test run trace

**Comment by kdhamric** [comment]
Can we just ‘dump’ the packets unless the trace backend is set to
opentelemetry collector?

**Comment by kdhamric** [comment]
Should we just 'dump' the spans as they come in unless we have the Opentelemetry collector mode set to on?
