### ISSUE TITLE
Explore how to integrate with Keptn

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1772]
## Exploration

Find out how we can provide a way for users to trigger a Tracetest operation to assert service correctness via Keptn,

They have an open issue about [Trace SLOs](https://github.com/keptn/lifecycle-toolkit/issues/508) and it has some content on how we can start the exploration.

**Comment by mathnogueira** [comment]
[Webhooks](https://keptn.sh/docs/1.0.x/integrations/webhooks/) seem to be the best way for us to integrate with Keptn. They require some data to be sent to the webhook. We would have to find a way of supporting webhooks and allowing different integrations to use the same webhook structure, but make Tracetest capable of sending different data to different integrations.

**Comment by danielbdias** [comment]
Another strategy that we can use is to use [`keptn-contrib/job-executor-service`](https://github.com/keptn-contrib/job-executor-service) on Keptn. 

With this plugin we are able to run docker commands whenever `keptn` emit certain events, allowing the user for instance, to set up a `test-task` into a keptn, which will emit the event `sh.keptn.event.test-task.triggered` and run tracetest.

**Comment by danielbdias** [comment]
To integrate with Keptn now we opted to use [keptn-contrib/job-executor-service](https://github.com/keptn-contrib/job-executor-service) since a user can configure freely how they can use Tracetest inside Keptn.

Our first documentation is ready at: https://github.com/kubeshop/tracetest/tree/main/examples/keptn-integration , that we submitted as documentation to Keptn Community and we will present at their community meeting next week.

Our next steps on this initiative are:
- #1881 
- #1837
- #1883 
- #1882
