### ISSUE TITLE
Add link to expressions docs in output form

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1809]
We need to add ability to show the attribute value for the output creation flow (check the explanation here https://www.loom.com/share/dee56fac8c7048379677639c78d2d18d)

Here is the mockups https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1155%3A24684&t=xBnyBWmCTNFHldsX-1

**Comment by jorgeepc** [comment]
Hey @olha23 I don't think @kdhamric suggestion is related to your mockups. Ken is talking about adding a link (or help) to how to write `expressions`. 

Your mockups are about including the `Attribute` value in the flow. I didn't include it because of two reasons:
1. We already have a panel with the list of attributes and its values.
2. The value could be an expression and not just one attribute.

![Screenshot 2023-01-10 at 15 30 34](https://user-images.githubusercontent.com/3879892/211655904-4575d6a2-95ba-4bce-9526-df434a04aad3.png)

**Comment by olha23** [comment]
<img width="783" alt="Screenshot 2023-01-11 at 10 06 30 AM" src="https://user-images.githubusercontent.com/5725840/211826583-66be6bfb-f394-4ca0-868e-f7d678ef7aae.png">
in this case i think we can provide link for doc
