### ISSUE TITLE
Add honeycomb.io support as data store

### ISSUE THREAD

**Issue by mik3h0** [kubeshop/tracetest#1945]
**Honeycomb.io is a place traces might be pushed, I'd like to use tracetest with traces stored there **

**Comment by kdhamric** [comment]
Thanks Mike! We are focused on adding integrations to backend trace data stores - we will move Honeycomb.io up the list. Would you be available to test the integration once we get it setup?

**Comment by mathnogueira** [comment]
Hey @mik3h0! I was working on adding honeycomb as one of the supported data stores for Tracetest, but I reached a dead-end. In order for Tracetest to get a trace out of a data store, it requires the data store API to have an endpoint for querying traces. Honeycomb does have it, however, it's limited to the enterprise plan only.

This doesn't mean you cannot use Tracetest. You could still use the OpenTelemetry collector to send traces directly to your Tracetest instance.  Here are the [docs on how to configure your collector](https://docs.tracetest.io/configuration/connecting-to-data-stores/opentelemetry-collector) to so do.

**Comment by kdhamric** [comment]
@mathnogueira Can you provide a link to documentation on the API that you were trying to use?

**Comment by mathnogueira** [comment]
I was trying to use two APIs in order to get a trace from honeycomb:

1. [Queries API](https://docs.honeycomb.io/api/queries/): I'd build the query to fetch the specific trace we wanted to get
2. [Query Data API](https://docs.honeycomb.io/api/query-results/): So I could execute the query I just built. **This requires the enterprise plan**
