### ISSUE TITLE
Switching between spans

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2017]
Check the video here please https://www.loom.com/share/6bdc2fe244044f1798f8447d5562e5f0

**Comment by xoscar** [comment]
Let's bring this up during our next planning session, we need to consider what happens if the test spec already has some assertions which don't match with the newly selected span?

Same for edit mode, should something like this be possible?

Also, we can propose new and better ways to add spans to the selector by interacting with the DAG.

**Comment by olha23** [comment]
updated mockups https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1920%3A29165&t=gBhenSQqNpOiOhtX-1

**Comment by olha23** [comment]
@xoscar @jorgeepc let’s implement this simple solution at first https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1920%3A29165&t=zGGIXBUcB85AtE7B-1

**Comment by kdhamric** [comment]
@xoscar @jorgeepc The action will be the same as clicking the 'Current span' link under the selector area.
