### ISSUE TITLE
Tracetest empty config file error

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2071]
Hey team, I found a bug while working on the Fargate provisioning for Tracetest, what happens is that the server always expects a config file to be available, and it throws an error and kills the server if it's not found.

Here's a video about the bug

https://www.loom.com/share/340a43cdfac44bad903b2c0560a10070

![Image](https://user-images.githubusercontent.com/11051031/222236264-6064a6af-a169-49e0-9cec-305e6f8b4dc9.png)

**Comment by schoren** [comment]
This was actually a very unexpected bug. we have the `tracetest` cli binary saved in the `/app/tracetest`. When tracetest-server starts, using `/app/` as the CWD, viper tries to find a config file in that directory. Apparently, setting the required config type by calling `vp.SetConfigType("yaml")` is not enough to enforce the file extension, so viper thought `/app/tracetest` was a valid config file path.

When `docker-compose.yaml` had the config file volume enabled, the `/app/tracetest.yaml` took precedence and the error didn't trigger.

This is fixed by https://github.com/kubeshop/tracetest/pull/2080. As an extra measure, I added a log to show the config file in use, if any. Might be useful for debugging similar errors in the future

**Comment by xoscar** [comment]
@schoren WTH haha makes sense, thanks for the fix!
