### ISSUE TITLE
Current default postgres image does not have an arm64 variant

### ISSUE THREAD

**Issue by ornell** [kubeshop/tracetest#2491]
**Describe the bug**
While deploying tracetest with the cli tooling on a arm64 based cluster the deployment fails due to the bitnami postgres image (14.6.0-debian-11-r13) currently used not support arm64. Leaving postgres in a crash loop.

**Browser (please complete the following information):**
 - N/A

**Additional context**
- Nodes are running on ARM64
- Ubuntu 23.04
- k3s

**Comment by adnanrahic** [comment]
Hi @ornell! Thanks for taking the time to open this issue!
We'll have a look and get back to you ASAP.

**Comment by schoren** [comment]
@ornell I wanted to let you know that we already updated our helm chart to use this version with ARM support. You can reinstall (or helm upgrade) tracetest and it shuold work now.

It'd be great if you could test the fix and confirm it's working, since I don't have access to a linux arm machine.

Thanks!
