### ISSUE TITLE
[Analyzer] Global Configuration - Test Run Failure Gates

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2686]
## Problem:

Determining if a test run should be considered passed or failed has become more complex with the addition of the Trace Analyzer. Before, if any assertion failed, the test failed. Now, it is a more complex decision, involving these questions:

Were there any assertions that failed? 
Is the trace analyzer on, and if so, was the overall score below the minimum? 
We may have a setting to say 'score the traces, show pass or fail for just the analyzer (visually), but do not fail the overall test (ie just show scores and whether we passed or not).

If we do not have a 'pass/fail' in the json response stored with a test run and returned when doing a GET of it, we may want to consider that.

CLI runs in particular will need cmd args that specify how to judge pass / fail, allowing a user to decide 'per run' what to fail on:
- only based on analyzer
- only passed on test specs
- based on both (ie if either fails, fail the test)

Starting this issue as a statement of the problem - lets discuss and make a plan of how to address.

## Solution:

Server configuration will support "failure gates", which will be used by the test runner to evaluate if the test is failed or not, this will impact the CLI result status code and the FE visual for that test run.

Failure gates, will not stop the test runner execution but the ultimate result should be based on the results from each of the gates, in this case, the initial supported gates are:

- analyzer-score
- analyzer-rules
- test-specs

The status of the failure will be part of a separate field that clients could use to show the information to the user
Failure gates configuration should be persisted in every test run execution, allowing users to identify what were the criteria to fail/pass the test.

Global gates can be overwritten by the user for specific test execution, allowing CLI or FE users to specify the optional configuration before running a test.

## Extra information from comments:

1. We have gateable things. Right now it would only be the analyzer and the assertion runner.
2. Each gateable can decide if it failed or pass.
3. The test runner, functioning as an orchestrator, asks each of the available gates if they passed or failed.
4. The test runner has access to the user-specified configuration, based on it it decides if the test run is a pass or fail.
5. The test needs to pass all required gates

```[tasklist]
### Tasks
- [ ] https://github.com/kubeshop/tracetest/issues/2776
- [ ] https://github.com/kubeshop/tracetest/issues/2777
- [ ] https://github.com/kubeshop/tracetest/issues/2778
```

**Comment by xoscar** [comment]
- Tests should display the result based on how it was configured from the run
- Consider global vs test run/test based failure point configuration

**Comment by schoren** [comment]
based on our talk today, I think a good approach would be to implement the `Gate` concept @danielbdias brought up. I think it's the most flexible approach for this reasons:
1. it removes the "hardcoded" checks (i.e. `if (analyzer.fail OR spec.fail`)
2. it allows to add new gates in the future

So the configuration would be "gates required to pass". For example:

```
type: Config # or whatever we choose
spec:
  // ... setings
  requiredPassingGates:
    - specs
    -  analyzer
```

an implementation overview could be:
1. we have `gateable` things. right now it would only be the analyzer and the assertion runner.
4. each `gateable` can decide if it failed or pass.
5. the test runner, functioning as an orchestrator, asks each of the available `gateables` if they passed or failed.
6. the test runner has access to the user specified configuration, based on it it decides if the test run is a pass or fail.
7. the test needs to pass al required gates

the gates could be defined globally (on it's own resource? within the `Config` resource?), and then overwritten at test or run level, following the idea of TracePoller.

I think this approach is relatively safe to implement because it doesn't modify much of the existing code, it only adds on top of it.

Does this make sense?

**Comment by xoscar** [comment]
@schoren I agree with what you are pointing out, I think the tickets encapsulate that exact behavior, having "gates" to soft-fail a test (not actually stopping the execution).

I think if we follow this path the most sense would be to have the config resource persist in this setting. If we decide it would make sense to have it elsewhere in the future, let's try to make the implementation in a way it won't be painful haha

If you agree, we can mark this issue as ready for development.

**Comment by danielbdias** [comment]
Hi folks! I like this idea! (And I loved to see the `Gate` concept from our discussion 😄 )

Maybe we could create a `TestRunner` resource? (or something that remarks that this config is related to a Test/Transaction run)

**Comment by xoscar** [comment]
@danielbdias I think it would make sense to have it as part of a specific runner resource, my only concern is if we want to keep adding more and more resources that could possibly increase the complexity
