### ISSUE TITLE
View the JUnit results inside the app

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#721]
We have the ability to download the JUnit results via the CLI.  We need to be able to view it in the web app.  The cli tight now only supports downloading the result of the run you’re currently running. The app would make it easy to get older runs.

**Comment by olha23** [comment]
We have the ability to download the JUnit results via the CLI.  We need to be able to view it in the web app.  The cli tight now only supports downloading the result of the run you’re currently running. The app would make it easy to get older runs.

**Comment by kdhamric** [comment]
@mathnogueira @schoren Could you attach an example of what the output of the JUnit result looks like?

**Comment by xoscar** [comment]
@kdhamric could you confirm if we want to support the JUnit viewer or if we just want to have the download file functionality?

I think we agreed during planning that the viewer wasn't necessary and we wanted to trigger the download right away. But @olha23 mentioned that after the planning you asked her to create a design for the viewer. Could you help us clarify the requirements?

**Comment by kdhamric** [comment]
I want to use the same viewer as we are having for the 'view test definition'.  There really is not much of a use case (I think) for showing the junit results in the UI... it is a command line / runner type file.  The real reason is add it to the FE is to expose that the capability is there, and to introduce the concept of CI/CD via command line.  We will follow up this design with a couple informative links to our docs on the command line - ie showing this screen will give us an area to expose the fact that we have a command line, and point them to the right resource.
