### ISSUE TITLE
Test vanish from test list after edit/update

### ISSUE THREAD

**Issue by cescoferraro** [kubeshop/tracetest#985]
if I edit a test at the home page
and then navigate back to the home page
the test does not show on the list anymore

**Expected behavior**
the test should sho on the list

**Comment by cescoferraro** [comment]
[/loo](https://www.loom.com/share/949a517f7ec84e97836310a8aa5374ca)

**Comment by schoren** [comment]
This was caused by 2 converging issues:
1. When updating tests, the `CreatedAt` timestamp is not preserved, so the list order is modified.
2. FE is asking for the latest 20 tests, but it's not paginated.

So, when updating a test, it will be sent to the bottom because it's createdAt date gets zeroed, and since it's on a position below 20, it's not shown.

I created [this PR](https://github.com/kubeshop/tracetest/pull/992) to preserve the timestamp, and [this issue](https://github.com/kubeshop/tracetest/issues/991) to track the FE work
